apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc-01
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
