apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: locust-worker-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: locust-worker
  minReplicas: 10
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
