apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::531744930393:role/eksctl-ecommerce-eks-nodegroup-eco-NodeInstanceRole-H7v7Df2Bb6jH
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::531744930393:role/eksctl-ecommerce-eks-nodegroup-eco-NodeInstanceRole-VpG2STXJ5yb9
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
