## https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/configuration-file
config:
  service: |
    [SERVICE]
        Daemon Off
        Flush {{ .Values.flush }}
        Log_Level {{ .Values.logLevel }}
        Parsers_File /fluent-bit/etc/parsers.conf
        Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port {{ .Values.metricsPort }}
        Health_Check On

  ## https://docs.fluentbit.io/manual/pipeline/inputs
  inputs: |
    [INPUT]
        Name              tail
        Tag               kube.ecommerce.*
        Path              /var/log/containers/*ecommerce*.log
        Parser            cri
        DB                /var/log/flb_kube_ecommerce.db
        Mem_Buf_Limit     5MB
        Skip_Long_Lines   On
        Refresh_Interval  10

  ## https://docs.fluentbit.io/manual/pipeline/filters
  filters: |
    [FILTER]
        Name        parser
        Match       *
        Key_Name    message
        Parser      custom_parser

  ## https://docs.fluentbit.io/manual/pipeline/outputs
  outputs: |

    [OUTPUT]
        Name  kinesis_firehose
        Match *
        region ap-northeast-2
        delivery_stream ecommerce-accesslog-fluentbit-to-s3-parquet
        workers 2

    [OUTPUT]
        Name           kafka
        Match          *
        Brokers        b-3.chiholeemsk.xmm8ve.c2.kafka.ap-northeast-2.amazonaws.com:9092,b-4.chiholeemsk.xmm8ve.c2.kafka.ap-northeast-2.amazonaws.com:9092,b-6.chiholeemsk.xmm8ve.c2.kafka.ap-northeast-2.amazonaws.com:9092
        Topics         accesslog
        Timestamp_Key  @timestamp
        Retry_Limit    false
        rdkafka.log.connection.close false
        rdkafka.queue.buffering.max.kbytes 10240
        rdkafka.request.required.acks 1

# [OUTPUT]
#     Name cloudwatch_logs
#     Match   *
#     region ap-northeast-2
#     log_group_name fluent-bit-cloudwatch
#     log_stream_prefix from-fluent-bit-
#     auto_create_group On

# [OUTPUT]
#     Name  kinesis_firehose
#     Match *
#     region ap-northeast-2
#     delivery_stream ecommerce-accesslog
#     workers 2

# [OUTPUT]
#     Name  opensearch
#     Match kube.ecommerce.*
#     Host  vpc-test-aponilxfo5qn2nfe6mitxf2rxu.ap-northeast-2.es.amazonaws.com
#     Port  443
#     Index direct-accesslog
#     Suppress_Type_Name  On
#     AWS_Auth On
#     AWS_Region ap-northeast-2
#     tls     On

  # [OUTPUT]
  #     Name                         s3
  #     Match                        *
  #     bucket                       chiho-datalake
  #     region                       ap-northeast-2
  #     total_file_size              1M
  #     use_put_object               Off
  #     compression                  gzip
  #     s3_key_format                /ecommerce-fluentbit-accesslog/%Y/%m/%d/%H_%M_%S.gz


  ## https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/upstream-servers
  ## This configuration is deprecated, please use `extraFiles` instead.
  upstream: {}

  ## https://docs.fluentbit.io/manual/pipeline/parsers
  customParsers: |
    [PARSER]
        Name        custom_parser
        Format      regex
        Regex       ^(?<timestamp>.+)\s+-\s+INFO\s+-\s+(?<ip>.+:\d+)\s+-\s+"(?<http_method>[A-Z]+)\s+(?<http_path>.+) HTTP/1.1"\s+(?<http_status>\d+)
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z


  # This allows adding more files with arbitary filenames to /fluent-bit/etc/conf by providing key/value pairs.
  # The key becomes the filename, the value becomes the file content.
  extraFiles: {}
#     upstream.conf: |
#       [UPSTREAM]
#           upstream1
#
#       [NODE]
#           name       node-1
#           host       127.0.0.1
#           port       43000
#     example.conf: |
#       [OUTPUT]
#           Name example
#           Match foo.*
#           Host bar

