apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
        project: ecommerce
    spec:
      containers:
      - name: product
        image: color275/ecommerce-linux:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: DBUSER
          value: "appuser"
        - name: PASSWORD
          value: "Appuser12#$"
        - name: HOST
          value: "prod-chiholee-smartdba-cluster.cluster-cgkgybnzurln.ap-northeast-2.rds.amazonaws.com"
        - name: PORT
          value: "3306"
        - name: DBNAME
          value: "ecommerce"
        - name: HOST_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: ORDER_SERVICE
          value: "order"
          # value: "172.20.229.95"

