apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: product-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: product
  minReplicas: 5
  maxReplicas: 10
  targetCPUUtilizationPercentage: 30
