apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: provisioner1
  namespace: karpenter-inflate
spec:
  requirements:
  - key: karpenter.sh/capacity-type
    operator: In
    values: ["spot"]
  limits:
    resources:
      cpu: 1000
  provider:
    subnetSelector:
      karpenter.sh/discovery: ken-cluster
    securityGroupSelector:
      karpenter.sh/discovery: ken-cluster
  ttlSecondsAfterEmpty: 30
