apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: provisioner1
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["spot"]
  limits:
    resources:
      cpu: 1000
  provider:
    subnetSelector:
      karpenter.sh/discovery: ecommerce-eks
    securityGroupSelector:
      karpenter.sh/discovery: ecommerce-eks
  ttlSecondsAfterEmpty: 30
