apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  namespace: product
spec:
  replicas: 5
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
        project: ecommerce
    spec:
      containers:
      - name: product
        image: color275/ecommerce-linux
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        envFrom:
        - configMapRef:
            name: database-env-config
        env:
        - name: HOST_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: ORDER_SERVICE
          value: "order"
          # value: "172.20.229.95"

