apiVersion: v1
kind: ConfigMap
metadata:
  name: db-connect-config
data:
  ## MySQL
  # DBUSER: "appuser"
  # PASSWORD: "Appuser12#$"
  # PRIMARY_HOST: "ecommerce.cluster-cgkgybnzurln.ap-northeast-2.rds.amazonaws.com"
  # READONLY_HOST: "ecommerce.cluster-ro-cgkgybnzurln.ap-northeast-2.rds.amazonaws.com"
  # PORT: "3306"
  # DBNAME: "ecommerce"
  ## Postgresql
  DBUSER: "appuser"
  PASSWORD: "appuser12#$"
  PRIMARY_HOST: "pgbouncer-nlb-07d14cf23a4e020b.elb.ap-northeast-2.amazonaws.com"
  READONLY_HOST: "pgbouncer-nlb-07d14cf23a4e020b.elb.ap-northeast-2.amazonaws.com"
  PORT: "6432"
  DBNAME: "template1"

