version: '3.8'

services:
  mysql:
    build: .
    container_name: mysql
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: admin
      MYSQL_PASSWORD: Admin1234
      MYSQL_ROOT_PASSWORD: Admin1234
      TZ: 'Asia/Seoul'
    ports:
    - "33061:3306"
    volumes:
    - ./mysqldata:/var/lib/mysql

volumes:
  mysqldata:
    driver: local
